# Common parameters
tile_index:
  fpath: "D:/Data/pointclouds/2022/tiles/tile_index_lidar_2022_local.shp" # Path to the source extent file with a geometry column containing the extent of each tile and a column with an identifier for each raster file
  identifier: "tileid" # Column name used to uniquely identify a tile in the tile index


# Raster tiling parameters
raster_tiling:
  dir_in: "D:/Data/images/2022/RGBI/" # Path to input directory (containing geotiff raster files with .tif extension)
  dir_out: "D:/Data/images/2022/RGBI_BUFFERED/" # Path to output directory
  suffix_out: "_20cm_rgbi_buffered" # Suffix added to output files
  crs: "EPSG:2056" # Coordinate reference system
  buffer_width: 20.0 # Width of the buffer (in maps units) to apply around each tile (set to 0, if you do not want a buffer)


# Tree top detection parameters
tree_top_detection:
  dir_in_chm: "D:/Data/images/2022/CHM_BUFFERED/" # Path to input directory (containing geotiff raster files with .tif extension)
  dir_out: "D:/Data/treetops/20250129/" # Path to output directory
  suffix_out: "_tree_tops" # Suffix added to output files
  export_shapefile: True # Export detected tree tops to shapefile
  export_feather: True # Export detected tree tops to feather file
  radius_function: "lambda h: 0.28 * h**0.59" # Lambda function specifying the radius (as a function of height) for the maxima detection window, see canopy_peaks.py for details
  gaussian_filter_sigma: 1.0 # Standard deviation for the Gaussian kernel used to smooth the CHM, see canopy_peaks.py for details
  min_height: 2.0 # Minimum tree top height, see canopy_peaks.py for details
  verbose: True # Switch to print additional info in console
  fig: False # Switch to plot figures
  
